### ISSUE TITLE
Refreshing download request?

### ISSUE THREAD

**Issue by jens2121** [ibamacsr/sentinelsat#66] opened 2016-11-04 05:15 UTC
At the moment I requested an order for 35 sentinel images amounting to approx. 200GiB. It started well, but I think it got interrupted by either the server being down or an internet interruption. The problem is that this made the sentinel download request halt/stop over-night and it wouldn't continue (see image attached, this is where it got to).

Is there anyway to refresh the download request to end the connection and reattempt to resume where it left off? I know the script has a "max_attempts" setting however not sure that it covers this type of issue?

I did a speed test on the net and the internet was definitely OK, then I reset the command request and now it is downloading as expected.

Not quite sure if/how this can be resolved...should I perhaps attempt running the python API independently rather than running the request through the CLI? 

Thanks guys, and keep up the great work!!!

**Comment by Fernerkundung** [comment] 2016-11-04 09:19
If your connection is interrupted and you just search&download with the same parameters the expected behaviour of `sentinel search` is as follow:

1. Search scenes and start to download them.
2. If there is a file with matching filename allready downloaded but the size is smaller than queried from the SciHub it resumes the download.
3. If the filename and size matches but the MD5 checksum doesn't it deletes the file and starts the download from scratch

This was implemented due to the frequent outages of the SciHub. So in short - when the connection is interrupted just redo the same command from the CLI and you should be good to go.

>Is there anyway to refresh the download request to end the connection and reattempt to resume where it left off?

`sentinel search` pretty much just does that.

**Comment by jens2121** [comment] 2016-11-04 09:29
Thanks for the response!

Ok, yes I just closed the frozen download and then reran the CLI command and it has done as you said.

I may wrap the CLI command to run from a python command and track the download speed over periods and if the speed is stuck below 1KB/s then the script will close the CLI and reopen the CLI and run the same command to bypass the event experienced yesterday.

Thanks Kersten!

**Comment by Fernerkundung** [comment] 2016-11-04 10:30
This might be better done from within the Python API itself. In it's current state it saves the results of your search so you could restart the `.download_all` function everytime your speed drops below a threshold without having to search all the scenes again (and causing unnecessary load on the SciHub servers).

**Comment by jens2121** [comment] 2016-11-04 10:34
Then I will do that. Thanks Kersten!

**Comment by jens2121** [comment] 2016-11-04 11:36
Kersten,

I am having trouble using the PYTHON API itself to get any results through a query. When I provide the same search parameter in the CLI the results are available immediately and the download starts immediately, but with the Python API I get a "SentinelAPIError - Page not found".

The code I am testing is from your docs:
# connect to the API
from sentinelsat.sentinel import SentinelAPI, get_coordinates
from datetime import date
api = SentinelAPI('gti1', 'witherite477', 'https://scihub.copernicus.eu/dhus')

# search by polygon, time, and SciHub query keywords
api.query(get_coordinates(' F:\SENTINEL-2_DATA\GEOJSON_CONVERSION_TEST\Delmas.geojson'), \
          "20161101", date(2016, 11, 01), \
          keywords={"platformname": "Sentinel-2", \
                    "cloudcoverpercentage": "[0 TO 20]"})

Any suggestions? I do realise that I could restart the query until I get results, but I am not quite sure why the CLI is has quick access to the search results, while the API can't find the page?

Any help would be appreciated.

FYI: The testing is done through a Python IDLE and not in a stand-alone script.

Cheers

Jens

**Comment by Fernerkundung** [comment] 2016-11-06 14:29
@jens2121 

- You should quicky remove your username and passwort from the example you posted - the code snippet as well as the screenshot. Or better yet change your password - immediately! (alternatively - @willemarcel can you edit them out please?)
- Are you using the newest version `0.7.1`?
- The PythonAPI and the CLI are functionally identical. The CLI ist just a wrapper around the most common way to use the API.
- The Search date in your CLI query (`20151101`) is not the same as in the API query (`20161101`). Also the maximum cloud cover is different - `20` in the API query and `50` in the CLI query.

**Comment by jens2121** [comment] 2016-11-06 17:06
Ok edited out the password and will change the password.

I am using the newest version 0.7.1.

I thought as much (that the cli is just a wrapper of the python api). Apologies the example I pasted was not an identical query (cli vs api), however the testing I had done was an identical query and I always seem to get an error. I will test again on my side and provide feedback.

**Comment by j08lue** [comment] 2017-01-19 15:29
> In it's current state it saves the results of your search so you could restart the .download_all function everytime your speed drops below a threshold without having to search all the scenes again (and causing unnecessary load on the SciHub servers).

NB: It might happen soon that you will need to handle the list of queried products yourself and cannot rely on `api` saving it (#81). Then (not yet!) you will need to do something like

    products = api.query(...)
    while some_check:
        api.download_all(products)
        time.sleep(600)

> api = SentinelAPI('gti1', '##########', 'https://scihub.copernicus.eu/dhus')

@jens2121 Does your problem go away when you remove the `api_url` and just do

    api = SentinelAPI('gti1', '##########')

?

**Comment by Fernerkundung** [comment] 2017-03-08 08:08
@jens2121 Does this error still occur with the changes to product queries with versions >0.9?

**Comment by jens2121** [comment] 2017-03-08 13:07
Hi there, at the moment we revert to AWS for the imagery downloads. But thanks for your assistance

**Comment by Fernerkundung** [comment] 2017-03-08 13:42
@jens2121 In that case please be so kind and close this issue.

**Closed** 2017-03-08 13:49 UTC
