### ISSUE TITLE
api.download(<product_id>)

### ISSUE THREAD

**Issue by pominville** [ibamacsr/sentinelsat#21] opened 2015-12-12 00:36 UTC
Hi, 
first of all thanks for the useful tool. It already worked for me, but with the changes to the ESA data hub, I couldn't get it to run although installing the new version 0.5.1. Connecting seems to work using 
api = SentinelAPI('user', 'password', 'https://scihub.copernicus.eu/dhus')
but the line
api.download('b7489729-a383-42f3-a06d-acb3e6106dc6')
gives me the error
Invalid API response. Trying again in 3 minutes.
I retrieved the number with the commandline (sentinel search ...) and also with the online search tool, so it should be right.

Thanks for checking.

**Comment by Fernerkundung** [comment] 2015-12-13 17:11
Your Scihub URL is missing a trailing slash. Change it to 'https://scihub.copernicus.eu/dhus/' and the download works.

**Comment by pominville** [comment] 2015-12-13 20:45
Thanks, I changed it, but then the following error was raised:
pycurl.error: (1, 'Protocol "https" not supported or disabled in libcurl')
So I changed the single quotes to double quotes around the URL. Then no error is raised, a zip is created in the folder with 0 KB and no download takes place. Current code:
api = SentinelAPI('user', 'password', "https://scihub.copernicus.eu/dhus/")
api.download('b7489729-a383-42f3-a06d-acb3e6106dc6')
I work on a Windows7-64bit machine with Anaconda and Python2.7 by the way.

**Comment by Fernerkundung** [comment] 2015-12-14 09:53
Have you tried putting everything in double quotes? Windows often dislikes single quotes (that's what caused your pycurl error btw).

**Comment by pominville** [comment] 2015-12-15 23:20
Yes, I tried, but the best I can achieve is a "download" of a zero-KB-zip (with no errors indicated by Python), which is visible in the file system. The messages I get are:
C:\Anaconda2\python.exe D:/zmon/geodata/sentinel1_processor.py
Downloading 6d4406d9-42e9-420b-a1f1-131857d1d236 to .\S1A_IW_GRDH_1SDV_20150329T162400_20150329T162425_005249_006A14_499F.zip

Process finished with exit code 0

**Comment by Fernerkundung** [comment] 2015-12-16 08:25
Can you share the relevant contents of sentinel1_processor.py as a gist (minus your user credentials)? I'd like to look into this further since we are using condas pycurl without problems on our Windows machines.

**Comment by pominville** [comment] 2015-12-16 21:54
No I am not trying to download more than 2. Actually I would be happy with one :-) The python-file does not contain any additional code relevant for the download, this is everything (I isolated this in a separate file): 
from sentinelsat.sentinel import SentinelAPI
api = SentinelAPI('user', 'password', "https://scihub.copernicus.eu/dhus/")
api.download('6d4406d9-42e9-420b-a1f1-131857d1d236')

I think the problem is related to missing support of https of curl, which is not included in the version information: 
[Anaconda2] D:\>curl -u user:password https://scihub.copernicus.eu/dhus/odat
a/v1/Products('18f7993d-eae1-4f7f-9d81-d7cf19c18378')/$value
curl: (1) Protocol "https" not supported or disabled in libcurl

[Anaconda2] D:\>curl --version
curl 7.45.0 (x86_64-pc-win32) libcurl/7.45.0 zlib/1.2.8
Protocols: dict file ftp gopher http imap ldap pop3 rtsp smb smtp telnet tftp
Features: AsynchDNS IPv6 Largefile SSPI Kerberos SPNEGO NTLM libz

I also installed certifi, version: 2015.11.20.1
I could not manage to support the https protocol.

**Comment by Fernerkundung** [comment] 2015-12-17 07:44
So this is not a `sentinelsat` but rather a `curl` issue.

Certifi only manages the certificate files - not the https support itself. If you can't find a conda (py)curl version that supports https I'd suggest trying to install one of the [pycurl wheels](http://www.lfd.uci.edu/~gohlke/pythonlibs/#pycurl) by Christoph Gohlke and remove condas version.

```bash
conda remove curl pycurl
pip install pycurl.whl
```

**Comment by pominville** [comment] 2015-12-22 00:18
That worked perfectly! Thanks a lot.
For the record, curl now includes https:
[Anaconda2] D:\>curl --version
curl 7.37.0 (Windows) libcurl/7.37.0 OpenSSL/1.0.2d zlib/1.2.8
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smtp
smtps telnet tftp
Features: NTLM SSL libz

**Comment by Fernerkundung** [comment] 2015-12-22 08:09
Glad to hear the issue is solved.
@pominville or @willemarcel, would you mind closing it as it is solved?

**Closed** 2015-12-22 14:36 UTC
